# Generated by Django 3.2 on 2022-11-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Producto')),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(upload_to='productos')),
                ('categoria', models.CharField(choices=[('VM', 'Vestimenta'), ('CA', 'Calzado'), ('AC', 'Accesorios'), ('SU', 'Suplementos')], max_length=2)),
                ('talle', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True)),
                ('info', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('subcategoria', models.CharField(blank=True, choices=[('RC', 'Remeras & Chombas'), ('BS', 'Bermudas & Shorts'), ('BC', 'Buzos & Camperas'), ('PC', 'Pantalones & Calzas'), ('MO', 'Moda'), ('EN', 'Entenamiento')], max_length=2, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['nombre'],
            },
        ),
    ]
