# Generated by Django 3.2 on 2022-11-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='opciones_calzado',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='opciones_vestimenta',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='suplemento',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
