# Generated by Django 3.2 on 2022-10-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(upload_to='calzado')),
                ('talle', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('info', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(choices=[('RC', 'Remeras & Chombas'), ('BS', 'Bermudas & Shorts'), ('BC', 'Buzos & Camperas'), ('PC', 'Pantalones & Calzas'), ('CA', 'Calzado'), ('AC', 'Accesorios'), ('SU', 'Suplementos')], max_length=2)),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Calzado',
        ),
    ]
