# Generated by Django 3.2 on 2022-11-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tienda', '0002_auto_20221107_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='calzado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='suplemento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='vestimenta',
            name='categoria',
        ),
    ]
