# Generated by Django 4.1.2 on 2022-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tienda', '0004_auto_20221024_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('RC', 'Remeras & Chombas'), ('BS', 'Bermudas & Shorts'), ('BC', 'Buzos & Camperas'), ('PC', 'Pantalones & Calzas')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('VM', 'Vestimenta'), ('CA', 'Calzado'), ('AC', 'Accesorios'), ('SU', 'Suplementos')], max_length=2),
        ),
    ]
