# Generated by Django 3.2 on 2022-10-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tienda', '0005_item_subcategoria_alter_item_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('RC', 'Remeras & Chombas'), ('BS', 'Bermudas & Shorts'), ('BC', 'Buzos & Camperas'), ('PC', 'Pantalones & Calzas'), ('MO', 'Moda'), ('EN', 'Entenamiento')], max_length=2, null=True),
        ),
    ]
